USE digital_lab;

INSERT INTO review VALUES(1, "ottimo", 5);
INSERT INTO review VALUES(1, "scarsa durata della batteria", 2);
INSERT INTO review VALUES(2, "ottima qualità costruttiva", 5);
INSERT INTO review VALUES(2, "buono", 4);
INSERT INTO review VALUES(3, "facile da usare", 4);
INSERT INTO review VALUES(3, "sufficiente", 3);
INSERT INTO review VALUES(4, "prestazioni deludenti", 2);
INSERT INTO review VALUES(4, "deludente", 2);
INSERT INTO review VALUES(5, "eccellente rapporto qualità-prezzo", 5);
INSERT INTO review VALUES(5, "scadente", 1);
INSERT INTO review VALUES(6, "funzionalità avanzate", 4);
INSERT INTO review VALUES(6, "affidabile", 5);
INSERT INTO review VALUES(7, "instabile", 2);
INSERT INTO review VALUES(7, "veloce", 4);
INSERT INTO review VALUES(8, "velocità di connessione superiore", 5);
INSERT INTO review VALUES(8, "prestazioni eccellenti", 5);
INSERT INTO review VALUES(9, "ottimo rapporto qualità-prezzo", 4);
INSERT INTO review VALUES(9, "design elegante", 4);
INSERT INTO review VALUES(10, "difficoltà di installazione", 1);
INSERT INTO review VALUES(10, "difetti minori", 3);
INSERT INTO review VALUES(11, "problemi di compatibilità", 2);
INSERT INTO review VALUES(11, "ottima qualità video", 5);
INSERT INTO review VALUES(12, "dimensioni compatte", 4);
INSERT INTO review VALUES(12, "pessima qualità costruttiva", 1);
INSERT INTO review VALUES(13, "facile da installare", 4);
INSERT INTO review VALUES(13, "scarso supporto software", 2);
INSERT INTO review VALUES(14, "ottima esperienza di gioco", 5);
INSERT INTO review VALUES(14, "buona durata della batteria", 5);
INSERT INTO review VALUES(15, "funzionalità limitate", 3);
INSERT INTO review VALUES(15, "connettività affidabile", 4);
INSERT INTO review VALUES(16, "problemi di surriscaldamento", 2);
INSERT INTO review VALUES(16, "scarso supporto clienti", 2);
INSERT INTO review VALUES(17, "efficiente", 5);
INSERT INTO review VALUES(17, "prezzo conveniente", 4);
INSERT INTO review VALUES(18, "funzionalità limitate", 3);
INSERT INTO review VALUES(18, "interfaccia utente intuitiva", 4);
INSERT INTO review VALUES(19, "scarso supporto clienti", 1);
INSERT INTO review VALUES(19, "problemi di surriscaldamento", 2);
INSERT INTO review VALUES(20, "qualità audio mediocre", 3);
INSERT INTO review VALUES(20, "prezzo elevato", 3);
INSERT INTO review VALUES(21, "ottima velocità di lettura/scrittura", 5);
INSERT INTO review VALUES(21, "ottima qualità audio", 4);
INSERT INTO review VALUES(22, "interfaccia utente poco intuitiva", 2);
INSERT INTO review VALUES(22, "facile da configurare", 5);